css-canvas-medical part 2 45% complete
ErikModica/c0121-code-solutions pull request #22
Opened 2021-01-25 19:06 UTC by ErikModica

2021-01-28 20:08 UTC, thebearingedge requested changes
Please let us know when it's done.

2021-01-28 22:47 UTC, ErikModica commented
![image](https://user-images.githubusercontent.com/76715055/106208062-a1e3de80-6177-11eb-9aeb-4de62f646e51.png)
![image](https://user-images.githubusercontent.com/76715055/106208094-af996400-6177-11eb-8435-c9414259bb5f.png)

2021-01-28 23:49 UTC, thebearingedge requested changes
Great work so far!

2021-01-28 23:49 UTC, thebearingedge commented on css-canvas-medical/styles.css
> +  src: url('TiemposHeadline-LightItalic.woff2') format('woff2');
The font family is already loaded, so you can leave out this `src` property.

2021-01-28 23:49 UTC, thebearingedge commented on css-canvas-medical/styles.css
> +  font-weight: 500;
I recommend consolidating your font settings like this:
```css
body,
button {
  font-family: 'Avenir', sans-serif;
}
```

That should help cut down on some duplication.

2021-01-28 23:49 UTC, thebearingedge commented on css-canvas-medical/styles.css
> +}
This is tough. There is a thing call a "hero" section. I'd use that for these areas with text over a background image. `row1`, `row2`, `row3` is not a good habit to get into. If you are having a hard time naming a section of the page, feel free to steal some of the content.

```css
.hero {

}

.hero-column {

}

.clinicians-prefer {

}
```

We want to get away from just numbering out classes, but naming is hard so we gotta get kind of creative.

2021-01-29 02:39 UTC, ErikModica commented
most recent push was just cleaning up css and chaning the class names to be more organized.

2021-01-29 18:34 UTC, thebearingedge approved these changes

2021-04-07 17:29 UTC, merged